name: Permissions
main: com.nijikokun.bukkit.Permissions.Permissions
depend: [ bPermissions ]
version: 2.7.7
authors: [ xu_robert, TheYeti, Nijiko ]
website: www.bukkit.org
description: Compatibility layer between original Permissions and bPermissions
